[package]
name = "seedplusplus"
version = "0.1.0"
authors = ["Rohan Mishra <rohanmishra2017@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
wasm-bindgen-macro = "0.2.70"

[dependencies]
seed = "0.8.0"

